# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # add more if you like

    steps:
      - uses: actions/checkout@v3

      # 1) Install the desired Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 2) Install pnpm and enable built-in cache
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # required
          run_install: false # we'll run pnpm install ourselves

      # 3) Install deps
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4) Lint (skip if no script)
      - name: Lint
        run: pnpm run lint --if-present

      # 5) Build
      - name: Build
        run: pnpm run build

      # 6) Test
      - name: Test
        run: pnpm test

      # 7) Coverage (optional)
      - name: Coverage
        run: pnpm run coverage --if-present
