name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      # Install Node + pnpm
      - uses: pnpm/action-setup@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: true # enables pnpm cache automatically

      # Restore pnpm store (optional with cache: true above)
      #- uses: actions/cache@v3
      #  with:
      #    path: ~/.pnpm-store
      #    key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - run: pnpm install --frozen-lockfile

      # Lint early to catch style errors
      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test

      - name: Coverage
        run: pnpm run coverage

      # (Optional) upload to Codecov
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
